site_name: SA Training and Basic Concepts
theme:
    name: readthedocs
nav:
    - Intro: index.md
    - Keywords: keywords.md
    - Keyword Services: services.md
    - Instrument Scripts: scripts.md
    - VNC Sessions: vnc_sessions.md
    - MAGIQ: magiq.md
    - Starlists: starlists.md
    - Target Acquisition: target_acquisition.md
    - FACSUM: facsum.md
    - KEOLA: keola.md
    - SIAS: sias.md
    - Focus: focus.md
    - conk: conk.md
    - KROOT: kroot.md
    - Nightlogs/Daylogs: nightlogs.md
    - OAs: oas.md
    - Observers: observers.md
    - Pointing Origins: pointing_origins.md
